# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: pypsa-earth
channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python>=3.8, <3.12  # 3.12 has weird issues with snakemake https://github.com/snakemake/snakemake/issues/2480
- pip
- mamba   # esp for windows build

- pypsa>=0.25, <=0.30.3
- atlite>=0.4.1
- dask
# currently the packages are being installed with pip
# need to move back to conda once the issues will be resolved
- powerplantmatching>=0.5.19
- earth-osm>=2.3.post1

# Dependencies of the workflow itself
- xlrd
- openpyxl
- seaborn
- snakemake-minimal<8
- memory_profiler
- ruamel.yaml<=0.17.26
- pytables
- pyscipopt
- lxml
- numpy<2
- pandas
- geopandas>=1
- fiona>=1.10
- xarray>=2023.11.0, <=2025.01.2
- netcdf4
- networkx
- scipy
- pydoe2
- shapely!=2.0.4
- pre-commit
- matplotlib
- reverse-geocode
- country_converter
- pyogrio
- numba
- py7zr
- tsam>=1.1.0
- fake-useragent
- chaospy

# Keep in conda environment when calling ipython
- ipython
# Jupyter notebook requirement
- ipykernel
- jupyterlab

# GIS dependencies:
- cartopy
- rasterio
- rioxarray

# Plotting
- geoviews
- hvplot
- graphviz
- contextily
- graphviz

# PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz
- country_converter

# Cloud download
# - googledrivedownloader  # Commented until https://github.com/conda-forge/googledrivedownloader-feedstock/pull/7 is merged: PR installed using pip

# Default solver for tests (required for CI)
- glpk
- gurobi

# Command Line Interface
- rich

- pip:
  - googledrivedownloader>=1.1
